---
title: "Interactive Tutorials"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Interactive Tutorials}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Interactive tutorials
```{r setup}
library(rxode2)
```

`rxode2` comes with a several interactive tutorials that you can run with
your own R session; They are built into Rstudio 1.3 and can be run
from any R session by:

```r
## rxode2 Syntax
learnr::run_tutorial("rxode2-00-syntax", "rxode2")

## rxode2 Event Tables 
learnr::run_tutorial("rxode2-01-events", "rxode2")

## rxode2 Model Functions (UI)
learnr::run_tutorial("rxode2-02-model-functions", "rxode2")

## rxode2 Piping and Modifying Models
learnr::run_tutorial("rxode2-03-piping-and-modifying", "rxode2")

## rxode2 Simulation
learnr::run_tutorial("rxode2-04-simulation", "rxode2")

## rxode2 Covariates and Data
learnr::run_tutorial("rxode2-05-covariates-and-data", "rxode2")

## rxode2 Advanced Features
learnr::run_tutorial("rxode2-06-advanced-features", "rxode2")
```
