test_that("rxProgress() rejects a bad count instead of crashing (#1377)", {
  expect_error(rxProgress(NULL))
  expect_error(rxProgress(integer(0)))
  expect_error(rxProgress(NA_integer_))
  expect_error(rxProgress(c(1L, 2L)))
  expect_error(rxProgress(-1L))
  expect_error(rxProgress(1.5))
  expect_error(rxProgress(10, core = integer(0)))
  expect_error(rxProgress(10, core = NA_integer_))
  expect_error(rxProgressStop(logical(0)))
  expect_error(rxProgressStop(NA))
  expect_error(rxProgressAbort(character(0)))
  expect_error(rxProgressAbort(1L))
})

test_that("the C entry points reject zero-length or mistyped arguments (#1377)", {
  expect_error(.Call(`_rxProgress`, NULL, 0L), "length 1")
  expect_error(.Call(`_rxProgress`, integer(0), 0L), "length 1")
  expect_error(.Call(`_rxProgress`, 1L, integer(0)), "length 1")
  expect_error(.Call(`_rxProgressStop`, integer(0)), "length 1")
  expect_error(.Call(`_rxProgressAbort`, character(0)), "length 1")
  expect_error(.Call(`_rxProgressAbort`, NULL), "length 1")
})

test_that("valid progress bar calls still work (#1377)", {
  expect_null(rxProgress(2))
  expect_type(rxTick(), "integer")
  expect_type(rxTick(), "integer")
  expect_null(rxProgressStop())
  expect_null(rxProgressAbort())
  expect_null(rxProgress(0L, core = 2))
  expect_null(rxProgressStop(FALSE))
  expect_null(rxProgressAbort("never shown"))
})
