rxTest({
  # rxFromSE()/rxToSE() are the text translators between rxode2 and symengine
  # syntax.  They are ~96% of all symbolic-derivative time and are being
  # reimplemented in C (dparser grammars), so this fixture pins their CURRENT
  # output: the C emitter must reproduce every string byte for byte, including
  # the quirks (`d^(-1)` -> `(1/(d))` but `a^(-2)` -> `a^-2`) and the error
  # messages.
  #
  # Fixture is generated by inst/tools/genSymengineFixture.R.  Regenerate it
  # ONLY when new syntax is added -- never to make a failing diff go away.

  .fixtureFile <- test_path("symengine-translate-fixture.rds")

  # a diff here means the translator changed behavior; show the offending
  # inputs rather than "576 != 576"
  .cmp <- function(df, fn, what) {
    .got <- character(nrow(df))
    .gotErr <- logical(nrow(df))
    for (.i in seq_len(nrow(df))) {
      .r <- tryCatch(fn(df$input[.i]),
                     error = function(e) {
                       .gotErr[.i] <<- TRUE
                       conditionMessage(e)
                     })
      .got[.i] <- if (is.character(.r) && length(.r) == 1L) .r else "<non-character>"
    }
    .bad <- which(.got != df$output | .gotErr != df$isError)
    if (length(.bad) > 0L) {
      .n <- min(length(.bad), 10L)
      .msg <- paste0(
        what, ": ", length(.bad), " of ", nrow(df), " translations changed\n",
        paste0("  input:    ", df$input[.bad[seq_len(.n)]], "\n",
               "  expected: ", df$output[.bad[seq_len(.n)]], "\n",
               "  got:      ", .got[.bad[seq_len(.n)]],
               collapse = "\n"))
    } else {
      .msg <- ""
    }
    list(nbad = length(.bad), msg = .msg, n = nrow(df))
  }

  test_that("the symengine translation fixture is present and non-trivial", {
    expect_true(file.exists(.fixtureFile))
    .f <- readRDS(.fixtureFile)
    expect_true(all(c("fromSE", "fromSEforward", "fromSEcentral", "toSE") %in%
                      names(.f)))
    # guard against a truncated/empty regeneration silently passing everything
    expect_gt(nrow(.f$fromSE), 400L)
    expect_gt(nrow(.f$toSE), 100L)
  })

  test_that("rxFromSE() reproduces the recorded output byte for byte", {
    .f <- readRDS(.fixtureFile)
    .r <- .cmp(.f$fromSE, function(x) rxode2::rxFromSE(x), "rxFromSE")
    expect_equal(.r$nbad, 0L, info = .r$msg)
  })

  test_that("rxFromSE() unknownDerivatives= modes are unchanged", {
    .f <- readRDS(.fixtureFile)
    .rf <- .cmp(.f$fromSEforward,
                function(x) rxode2::rxFromSE(x, "forward"), "rxFromSE(forward)")
    expect_equal(.rf$nbad, 0L, info = .rf$msg)
    .rc <- .cmp(.f$fromSEcentral,
                function(x) rxode2::rxFromSE(x, "central"), "rxFromSE(central)")
    expect_equal(.rc$nbad, 0L, info = .rc$msg)
  })

  test_that("the seFromSE grammar and the C kind map still agree", {
    # src/seFromSEnode.h maps production NAMES to kinds, and the walk then
    # relies on those kinds for meaning.  A grammar edit the map has not been
    # told about does not fail loudly, it changes answers: rename
    # power_expression and seIsBareNumber() stops seeing through it, so `d^2`
    # emits d^2 instead of Rx_pow_di(d,2).
    #
    # At runtime that is handled by refusing the C path entirely (rxFromSE()
    # falls back to the R walker, which is correct but slower).  This is where
    # it has to be noticed.  If this fails, update the `map` in
    # src/seFromSEnode.h to match inst/seFromSE.g -- do NOT delete the test.
    .problems <- .Call(`_rxode2_rxFromSEGrammarProblems`)
    expect_equal(length(.problems), 0L,
                 info = paste(.problems, collapse = "\n"))
  })

  test_that("the committed parser tables match inst/seFromSE.g", {
    # src/seFromSE.g.d_parser.h is generated from inst/seFromSE.g by
    # .rxodeBuildCode().  Editing the grammar without regenerating leaves the
    # emitter parsing the OLD language, which no drift check inside C can see.
    .g <- test_path("..", "..", "inst", "seFromSE.g")
    .h <- test_path("..", "..", "src", "seFromSE.g.d_parser.h")
    skip_if_not(file.exists(.g) && file.exists(.h),
                "source tree not available (installed package)")
    # every production the grammar defines must appear in the generated symbol
    # table; a rename or addition that was never regenerated shows up here
    .lines <- readLines(.g, warn = FALSE)
    .lines <- .lines[!grepl("^\\s*//", .lines)]
    # the grammar puts the production name on its own line and the ':' on the
    # next, so work on the joined text: a name is what follows the start or a
    # rule-ending ';'
    .txt <- paste(.lines, collapse = "\n")
    .prod <- regmatches(.txt, gregexpr(
      "(^|;)[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*:", .txt))[[1]]
    .prod <- unique(gsub("^[;[:space:]]*|[[:space:]]*:$", "", .prod))
    expect_gt(length(.prod), 10L)
    .tab <- paste(readLines(.h, warn = FALSE), collapse = "\n")
    .missing <- .prod[!vapply(.prod, function(p) {
      grepl(paste0('"', p, '"'), .tab, fixed = TRUE)
    }, logical(1))]
    expect_equal(length(.missing), 0L,
                 info = paste0("inst/seFromSE.g defines ",
                               paste(.missing, collapse = ", "),
                               " but src/seFromSE.g.d_parser.h does not have ",
                               "it; regenerate with .rxodeBuildCode()"))
  })

  test_that("the C emitter agrees with the R walker wherever it accepts", {
    # src/seFromSE.c returns NA_character_ for anything it does not reproduce
    # exactly, and rxFromSE() then falls back to .rxFromSE().  Declining is
    # always safe; disagreeing is not.  So the only thing to assert is that
    # every expression the C path DOES accept matches the recorded output.
    .f <- readRDS(.fixtureFile)
    .df <- .f$fromSE
    .got <- .Call(`_rxode2_rxFromSEChar`, .df$input, 1L)
    .h <- which(!is.na(.got))
    expect_gt(length(.h), 100L) # it must actually be doing something

    .bad <- .h[.got[.h] != .df$output[.h] | .df$isError[.h]]
    .msg <- ""
    if (length(.bad) > 0L) {
      .n <- min(length(.bad), 10L)
      .msg <- paste0(
        "C emitter disagrees on ", length(.bad), " of ", length(.h),
        " accepted expressions\n",
        paste0("  input:    ", .df$input[.bad[seq_len(.n)]], "\n",
               "  expected: ", .df$output[.bad[seq_len(.n)]], "\n",
               "  got:      ", .got[.bad[seq_len(.n)]], collapse = "\n"))
    }
    expect_equal(length(.bad), 0L, info = .msg)
  })

  test_that("rxFromSE() gives the same answer with the C path on and off", {
    .f <- readRDS(.fixtureFile)
    .in <- .f$fromSE$input[!.f$fromSE$isError]
    .withC <- withr::with_options(
      list(rxode2.symengineC = TRUE),
      vapply(.in, function(x) rxode2::rxFromSE(x), character(1), USE.NAMES = FALSE))
    .withR <- withr::with_options(
      list(rxode2.symengineC = FALSE),
      vapply(.in, function(x) rxode2::rxFromSE(x), character(1), USE.NAMES = FALSE))
    expect_equal(.withC, .withR)
  })

  test_that("rxToSE() reproduces the recorded output byte for byte", {
    .f <- readRDS(.fixtureFile)
    .r <- .cmp(.f$toSE, function(x) rxode2::rxToSE(x), "rxToSE")
    expect_equal(.r$nbad, 0L, info = .r$msg)
  })
})
